"""Create Product, Color models

Revision ID: f9a06b99767c
Revises: 
Create Date: 2023-04-12 20:40:32.190678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a06b99767c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('color_id')
    )
    op.create_table('product',
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('brand', sa.String(length=256), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('site_brand_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('sale', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedbacks', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nm_id')
    )
    op.create_table('product_color_bridge_table',
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['color.color_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nm_id'], ['product.nm_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nm_id', 'color_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_color_bridge_table')
    op.drop_table('product')
    op.drop_table('color')
    # ### end Alembic commands ###
