version: '3.8'

services:

  database:
    image: postgres:14.4-alpine
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres_parser_data:/var/lib/postgres/data
    environment:
      - DB_HOST=${DB_HOST-postgres-db}
      - DB_PORT=${DB_PORT-5432}
      - DB_ENGINE=${DB_ENGINE-postgresql+asyncpg}
      - DB_NAME=${DB_NAME-app_dev}
      - POSTGRES_USER=${POSTGRES_USER-app_dev}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-4HsnXp71Hbn0IsP}

  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ../:/opt/app/
    environment:
      - ALLOW_ORIGINS=${ALLOW_ORIGINS-'["http://localhost","http://localhost:8000"]'}

volumes:
  postgres_parser_data:
